# Generated by Django 2.0.1 on 2018-01-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('americano', models.IntegerField()),
                ('wifi', models.IntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
    ]
