# Generated by Django 2.0.1 on 2018-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('plug', models.IntegerField(choices=[(0, 'None'), (1, 'Some'), (2, 'Many')])),
                ('wifi', models.IntegerField(choices=[(0, 'Bad'), (1, 'Fine'), (2, 'Good')])),
                ('americano', models.IntegerField()),
                ('open_weekday', models.IntegerField()),
                ('open_sat', models.IntegerField()),
                ('open_sun', models.IntegerField()),
                ('close_weekday', models.IntegerField()),
                ('close_sat', models.IntegerField()),
                ('close_sun', models.IntegerField()),
            ],
        ),
    ]
