# Generated by Django 2.0.1 on 2018-01-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
