# Generated by Django 2.0.1 on 2018-01-26 14:05

from django.db import migrations, models
import django.db.models.deletion


def migrate_prices(apps, schema_editor):
    Cafe = apps.get_model("cafe", "Cafe")

    for cafe in Cafe.objects.all():
        cafe.prices_set.create(americano=cafe.americano)


def migrate_reviews(apps, schema_editor):
    Cafe = apps.get_model("cafe", "Cafe")
    
    for cafe in Cafe.objects.all():
        cafe.review_set.create(wifi=cafe.wifi, plug=cafe.plug)


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_weekday', models.IntegerField()),
                ('open_sat', models.IntegerField()),
                ('open_sun', models.IntegerField()),
                ('close_weekday', models.IntegerField()),
                ('close_sat', models.IntegerField()),
                ('close_sun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('americano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('plug', models.IntegerField(choices=[(0, 'None'), (1, 'Some'), (2, 'Many')])),
                ('wifi', models.IntegerField(choices=[(0, 'Bad'), (1, 'Fine'), (2, 'Good')])),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe'),
        ),
        migrations.AddField(
            model_name='prices',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe'),
        ),
        migrations.AddField(
            model_name='hours',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe'),
        ),
        migrations.RunPython(migrate_reviews),
        migrations.RunPython(migrate_prices),
        migrations.RemoveField(
            model_name='cafe',
            name='americano',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='close_sat',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='close_sun',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='close_weekday',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='open_sat',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='open_sun',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='open_weekday',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='plug',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='wifi',
        ),
    ]
