# Generated by Django 2.0.1 on 2018-01-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafe_comment'),
        ('cafe', '0003_auto_20180126_1405'),
    ]

    operations = [
    ]
